// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kfhfEU2lpFIo5FvG2HwubB__b19JGXY',
    appId: '1:863003295183:web:747edeacf35872f87ae6ba',
    messagingSenderId: '863003295183',
    projectId: 'klasskonnect-portal',
    authDomain: 'klasskonnect-portal.firebaseapp.com',
    storageBucket: 'klasskonnect-portal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_WqLXziATbEQLTAW7uOrUHJ-DUpeK97I',
    appId: '1:863003295183:android:00160db2a17d4c9d7ae6ba',
    messagingSenderId: '863003295183',
    projectId: 'klasskonnect-portal',
    storageBucket: 'klasskonnect-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmK3xneeBB0xDy7vGqfa-8Lug1sUDNgwo',
    appId: '1:863003295183:ios:00441ac0ea78fd147ae6ba',
    messagingSenderId: '863003295183',
    projectId: 'klasskonnect-portal',
    storageBucket: 'klasskonnect-portal.firebasestorage.app',
    iosBundleId: 'com.example.klasskonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmK3xneeBB0xDy7vGqfa-8Lug1sUDNgwo',
    appId: '1:863003295183:ios:00441ac0ea78fd147ae6ba',
    messagingSenderId: '863003295183',
    projectId: 'klasskonnect-portal',
    storageBucket: 'klasskonnect-portal.firebasestorage.app',
    iosBundleId: 'com.example.klasskonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_kfhfEU2lpFIo5FvG2HwubB__b19JGXY',
    appId: '1:863003295183:web:520c96ab8395fcb47ae6ba',
    messagingSenderId: '863003295183',
    projectId: 'klasskonnect-portal',
    authDomain: 'klasskonnect-portal.firebaseapp.com',
    storageBucket: 'klasskonnect-portal.firebasestorage.app',
  );
}
